### ISSUE TITLE
Site name vs Name

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_live_preview#1]
It looks like we have a site name and a group name.

![image](https://github.com/user-attachments/assets/0af991ca-0a64-4831-9d7f-77de0c4f78af)

![image](https://github.com/user-attachments/assets/07973252-99c2-4e3a-99b9-3fccd972bb36)

When editing the microsite settings, we seem to have a mismatch between the page title and the field we are editing.
![image](https://github.com/user-attachments/assets/08c93fb7-0adb-4919-84be-f37c72a871df)

**Comment by markconroy** [comment]
I'm not sure we can fix this in this module, as this module only loads the group/gid/edit page, not the group/gid/domain-settings page.

I added a small bit of JS to hide that field on this form when in the settings tray, but I think that's about all we can do.

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
