### ISSUE TITLE
UX of selecting colours

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_live_preview#2]
Sometimes when clicking into the colour selector, you need to click into the colour field first, or the colour is not sent to the css variable.  

![image](https://github.com/user-attachments/assets/dd3f1b22-528c-4265-847b-a92e15684c03)

**Comment by markconroy** [comment]
This should be fixed now via https://github.com/localgovdrupal/localgov_live_preview/commit/016524cbaf6952725efddb8aefe0933495c30d4b

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
